sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=codestyle
    - python: 2.7
      env: TOXENV=pypi-lint

install: pip install tox
script: tox
